spring.application.name=backend

server.port=${SERVER_PORT:8080}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/abcerpdb}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# Notice file upload
notice.upload.path=${NOTICE_UPLOAD_PATH:uploads/notice}

# Multipart upload limit
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:100MB}

# CORS / WebSocket origin
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}
app.websocket.allowed-origin=${WEBSOCKET_ALLOWED_ORIGIN:http://localhost:5173}

# Performance logging , API 응답시간 로그 출력
app.performance.logging.enabled=${PERFORMANCE_LOGGING_ENABLED:true}


# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Member cache
# Cache switch , Redis 캐시 On / Off 설정
app.cache.member.enabled=${MEMBER_CACHE_ENABLED:false}
app.cache.member.ttl-minutes=${MEMBER_CACHE_TTL_MINUTES:10}
# Refresh Token (디폴트 1일)
app.auth.refresh-token.ttl-minutes=${REFRESH_TOKEN_TTL_MINUTES:1440}